### ISSUE TITLE
Hi Gustavo

### ISSUE THREAD

**Issue by MastermindJapan** [gabranches/skeleton-typescript-jest-tslint#28]
Hi Gustavo, 

I couldn't find any other ways to contact you. I see that you're a project owner for Simpleddit.

I recently noticed that the page is no longer accessible.

If you have the time and interest still, can you please look into this? I truly appreciate the website and would love for it to be available again.

Thanks!

**Comment by gabranches** [comment]
Hi,

I appreciate the message. Unfortunately, Simpleddit was an old project that I have not maintained for a long time - I'm surprised that it stayed up for as long as it did! I'm sorry but I don't have any plans to get the site back up and running at the moment, for both time and monetary reasons.

I'm happy that you found the site useful!

Best,
Gustavo
